# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20170630_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': '\u041f\u0440\u043e\u0444\u0438\u043b\u044c', 'verbose_name_plural': '\u041f\u0440\u043e\u0444\u0438\u043b\u0438'},
        ),
    ]
